using Taxes.Shared.Abstractions.Kernel.Enums;
using System.Collections.Generic;

namespace Taxes.Shared.Abstractions.Kernel.Entites
{
    public static class GenericData
    {
        public static IList<Country> Countries = new List<Country>()
        {
                  new Country { Name = "Afghanistan", Code = "AF", Demonym="" },
                  new Country { Name = "Åland Islands", Code = "AX", Demonym="" },
                  new Country { Name = "Albania", Code = "AL", Demonym="" },
                  new Country { Name = "Algeria", Code = "DZ", Demonym="" },
                  new Country { Name = "American Samoa", Code = "AS", Demonym="" },
                  new Country { Name = "AndorrA", Code = "AD", Demonym="" },
                  new Country { Name = "Angola", Code = "AO", Demonym="" },
                  new Country { Name = "Anguilla", Code = "AI", Demonym="" },
                  new Country { Name = "Antarctica", Code = "AQ", Demonym="" },
                  new Country { Name = "Antigua and Barbuda", Code = "AG", Demonym="" },
                  new Country { Name = "Argentina", Code = "AR", Demonym="" },
                  new Country { Name = "Armenia", Code = "AM", Demonym="" },
                  new Country { Name = "Aruba", Code = "AW", Demonym="" },
                  new Country { Name = "Australia", Code = "AU", Demonym="" },
                  new Country { Name = "Austria", Code = "AT", Demonym="" },
                  new Country { Name = "Azerbaijan", Code = "AZ", Demonym="" },
                  new Country { Name = "Bahamas", Code = "BS", Demonym="" },
                  new Country { Name = "Bahrain", Code = "BH", Demonym="" },
                  new Country { Name = "Bangladesh", Code = "BD", Demonym="" },
                  new Country { Name = "Barbados", Code = "BB", Demonym="" },
                  new Country { Name = "Belarus", Code = "BY", Demonym="" },
                  new Country { Name = "Belgium", Code = "BE", Demonym="" },
                  new Country { Name = "Belize", Code = "BZ", Demonym="" },
                  new Country { Name = "Benin", Code = "BJ", Demonym="" },
                  new Country { Name = "Bermuda", Code = "BM", Demonym="" },
                  new Country { Name = "Bhutan", Code = "BT", Demonym="" },
                  new Country { Name = "Bolivia", Code = "BO", Demonym="" },
                  new Country { Name = "Bosnia and Herzegovina", Code = "BA", Demonym="" },
                  new Country { Name = "Botswana", Code = "BW", Demonym="" },
                  new Country { Name = "Bouvet Island", Code = "BV", Demonym="" },
                  new Country { Name = "Brazil", Code = "BR", Demonym="" },
                  new Country { Name = "British Indian Ocean Territory", Code = "IO", Demonym="" },
                  new Country { Name = "Brunei Darussalam", Code = "BN", Demonym="" },
                  new Country { Name = "Bulgaria", Code = "BG", Demonym="" },
                  new Country { Name = "Burkina Faso", Code = "BF", Demonym="" },
                  new Country { Name = "Burundi", Code = "BI", Demonym="" },
                  new Country { Name = "Cambodia", Code = "KH", Demonym="" },
                  new Country { Name = "Cameroon", Code = "CM", Demonym="" },
                  new Country { Name = "Canada", Code = "CA", Demonym="" },
                  new Country { Name = "Cape Verde", Code = "CV", Demonym="" },
                  new Country { Name = "Cayman Islands", Code = "KY", Demonym="" },
                  new Country { Name = "Central African Republic", Code = "CF", Demonym="" },
                  new Country { Name = "Chad", Code = "TD", Demonym="" },
                  new Country { Name = "Chile", Code = "CL", Demonym="" },
                  new Country { Name = "China", Code = "CN", Demonym="" },
                  new Country { Name = "Christmas Island", Code = "CX", Demonym="" },
                  new Country { Name = "Cocos (Keeling) Islands", Code = "CC", Demonym="" },
                  new Country { Name = "Colombia", Code = "CO", Demonym="" },
                  new Country { Name = "Comoros", Code = "KM", Demonym="" },
                  new Country { Name = "Congo", Code = "CG", Demonym="" },
                  new Country { Name = "Congo, The Democratic Republic of the", Code = "CD", Demonym="" },
                  new Country { Name = "Cook Islands", Code = "CK", Demonym="" },
                  new Country { Name = "Costa Rica", Code = "CR", Demonym="" },
                  new Country { Name = "Cote D\"Ivoire", Code = "CI", Demonym="" },
                  new Country { Name = "Croatia", Code = "HR", Demonym="" },
                  new Country { Name = "Cuba", Code = "CU", Demonym="" },
                  new Country { Name = "Cyprus", Code = "CY", Demonym="" },
                  new Country { Name = "Czech Republic", Code = "CZ", Demonym="" },
                  new Country { Name = "Denmark", Code = "DK", Demonym="" },
                  new Country { Name = "Djibouti", Code = "DJ", Demonym="" },
                  new Country { Name = "Dominica", Code = "DM", Demonym="" },
                  new Country { Name = "Dominican Republic", Code = "DO", Demonym="" },
                  new Country { Name = "Ecuador", Code = "EC", Demonym="" },
                  new Country { Name = "Egypt", Code = "EG", Demonym="" },
                  new Country { Name = "El Salvador", Code = "SV", Demonym="" },
                  new Country { Name = "Equatorial Guinea", Code = "GQ", Demonym="" },
                  new Country { Name = "Eritrea", Code = "ER", Demonym="" },
                  new Country { Name = "Estonia", Code = "EE", Demonym="" },
                  new Country { Name = "Ethiopia", Code = "ET", Demonym="" },
                  new Country { Name = "Falkland Islands (Malvinas)", Code = "FK", Demonym="" },
                  new Country { Name = "Faroe Islands", Code = "FO", Demonym="" },
                  new Country { Name = "Fiji", Code = "FJ", Demonym="" },
                  new Country { Name = "Finland", Code = "FI", Demonym="" },
                  new Country { Name = "France", Code = "FR", Demonym="" },
                  new Country { Name = "French Guiana", Code = "GF", Demonym="" },
                  new Country { Name = "French Polynesia", Code = "PF", Demonym="" },
                  new Country { Name = "French Southern Territories", Code = "TF", Demonym="" },
                  new Country { Name = "Gabon", Code = "GA", Demonym="" },
                  new Country { Name = "Gambia", Code = "GM", Demonym="" },
                  new Country { Name = "Georgia", Code = "GE", Demonym="" },
                  new Country { Name = "Germany", Code = "DE", Demonym="" },
                  new Country { Name = "Ghana", Code = "GH", Demonym="" },
                  new Country { Name = "Gibraltar", Code = "GI", Demonym="" },
                  new Country { Name = "Greece", Code = "GR", Demonym="" },
                  new Country { Name = "Greenland", Code = "GL", Demonym="" },
                  new Country { Name = "Grenada", Code = "GD", Demonym="" },
                  new Country { Name = "Guadeloupe", Code = "GP", Demonym="" },
                  new Country { Name = "Guam", Code = "GU", Demonym="" },
                  new Country { Name = "Guatemala", Code = "GT", Demonym="" },
                  new Country { Name = "Guernsey", Code = "GG", Demonym="" },
                  new Country { Name = "Guinea", Code = "GN", Demonym="" },
                  new Country { Name = "Guinea-Bissau", Code = "GW", Demonym="" },
                  new Country { Name = "Guyana", Code = "GY", Demonym="" },
                  new Country { Name = "Haiti", Code = "HT", Demonym="" },
                  new Country { Name = "Heard Island and Mcdonald Islands", Code = "HM", Demonym="" },
                  new Country { Name = "Holy See (Vatican City State)", Code = "VA", Demonym="" },
                  new Country { Name = "Honduras", Code = "HN", Demonym="" },
                  new Country { Name = "Hong Kong", Code = "HK", Demonym="" },
                  new Country { Name = "Hungary", Code = "HU", Demonym="" },
                  new Country { Name = "Iceland", Code = "IS", Demonym="" },
                  new Country { Name = "India", Code = "IN", Demonym="" },
                  new Country { Name = "Indonesia", Code = "ID", Demonym="" },
                  new Country { Name = "Iran, Islamic Republic Of", Code = "IR", Demonym="" },
                  new Country { Name = "Iraq", Code = "IQ", Demonym="" },
                  new Country { Name = "Ireland", Code = "IE", Demonym="" },
                  new Country { Name = "Isle of Man", Code = "IM", Demonym="" },
                  new Country { Name = "Israel", Code = "IL", Demonym="" },
                  new Country { Name = "Italy", Code = "IT", Demonym="" },
                  new Country { Name = "Jamaica", Code = "JM", Demonym="" },
                  new Country { Name = "Japan", Code = "JP", Demonym="" },
                  new Country { Name = "Jersey", Code = "JE", Demonym="" },
                  new Country { Name = "Jordan", Code = "JO", Demonym="" },
                  new Country { Name = "Kazakhstan", Code = "KZ", Demonym="" },
                  new Country { Name = "Kenya", Code = "KE", Demonym="" },
                  new Country { Name = "Kiribati", Code = "KI", Demonym="" },
                  new Country { Name = "Korea, Democratic People\"S Republic of", Code = "KP", Demonym="" },
                  new Country { Name = "Korea, Republic of", Code = "KR", Demonym="" },
                  new Country { Name = "Kuwait", Code = "KW", Demonym="" },
                  new Country { Name = "Kyrgyzstan", Code = "KG", Demonym="" },
                  new Country { Name = "Lao People\"S Democratic Republic", Code = "LA", Demonym="" },
                  new Country { Name = "Latvia", Code = "LV", Demonym="" },
                  new Country { Name = "Lebanon", Code = "LB", Demonym="" },
                  new Country { Name = "Lesotho", Code = "LS", Demonym="" },
                  new Country { Name = "Liberia", Code = "LR", Demonym="" },
                  new Country { Name = "Libyan Arab Jamahiriya", Code = "LY", Demonym="" },
                  new Country { Name = "Liechtenstein", Code = "LI", Demonym="" },
                  new Country { Name = "Lithuania", Code = "LT", Demonym="" },
                  new Country { Name = "Luxembourg", Code = "LU", Demonym="" },
                  new Country { Name = "Macao", Code = "MO", Demonym="" },
                  new Country { Name = "Macedonia, The Former Yugoslav Republic of", Code = "MK", Demonym="" },
                  new Country { Name = "Madagascar", Code = "MG", Demonym="" },
                  new Country { Name = "Malawi", Code = "MW", Demonym="" },
                  new Country { Name = "Malaysia", Code = "MY", Demonym="" },
                  new Country { Name = "Maldives", Code = "MV", Demonym="" },
                  new Country { Name = "Mali", Code = "ML", Demonym="" },
                  new Country { Name = "Malta", Code = "MT", Demonym="" },
                  new Country { Name = "Marshall Islands", Code = "MH", Demonym="" },
                  new Country { Name = "Martinique", Code = "MQ", Demonym="" },
                  new Country { Name = "Mauritania", Code = "MR", Demonym="" },
                  new Country { Name = "Mauritius", Code = "MU", Demonym="" },
                  new Country { Name = "Mayotte", Code = "YT", Demonym="" },
                  new Country { Name = "Mexico", Code = "MX", Demonym="" },
                  new Country { Name = "Micronesia, Federated States of", Code = "FM", Demonym="" },
                  new Country { Name = "Moldova, Republic of", Code = "MD", Demonym="" },
                  new Country { Name = "Monaco", Code = "MC", Demonym="" },
                  new Country { Name = "Mongolia", Code = "MN", Demonym="" },
                  new Country { Name = "Montserrat", Code = "MS", Demonym="" },
                  new Country { Name = "Morocco", Code = "MA", Demonym="" },
                  new Country { Name = "Mozambique", Code = "MZ", Demonym="" },
                  new Country { Name = "Myanmar", Code = "MM", Demonym="" },
                  new Country { Name = "Namibia", Code = "NA", Demonym="" },
                  new Country { Name = "Nauru", Code = "NR", Demonym="" },
                  new Country { Name = "Nepal", Code = "NP", Demonym="" },
                  new Country { Name = "Netherlands", Code = "NL", Demonym="" },
                  new Country { Name = "Netherlands Antilles", Code = "AN", Demonym="" },
                  new Country { Name = "New Caledonia", Code = "NC", Demonym="" },
                  new Country { Name = "New Zealand", Code = "NZ", Demonym="" },
                  new Country { Name = "Nicaragua", Code = "NI", Demonym="" },
                  new Country { Name = "Niger", Code = "NE", Demonym="" },
                  new Country { Name = "Nigeria", Code = "NG", Demonym="" },
                  new Country { Name = "Niue", Code = "NU", Demonym="" },
                  new Country { Name = "Norfolk Island", Code = "NF", Demonym="" },
                  new Country { Name = "Northern Mariana Islands", Code = "MP", Demonym="" },
                  new Country { Name = "Norway", Code = "NO", Demonym="" },
                  new Country { Name = "Oman", Code = "OM", Demonym="" },
                  new Country { Name = "Pakistan", Code = "PK", Demonym="" },
                  new Country { Name = "Palau", Code = "PW", Demonym="" },
                  new Country { Name = "Palestinian Territory, Occupied", Code = "PS", Demonym="" },
                  new Country { Name = "Panama", Code = "PA", Demonym="" },
                  new Country { Name = "Papua New Guinea", Code = "PG", Demonym="" },
                  new Country { Name = "Paraguay", Code = "PY", Demonym="" },
                  new Country { Name = "Peru", Code = "PE", Demonym="" },
                  new Country { Name = "Philippines", Code = "PH", Demonym="" },
                  new Country { Name = "Pitcairn", Code = "PN", Demonym="" },
                  new Country { Name = "Poland", Code = "PL", Demonym="" },
                  new Country { Name = "Portugal", Code = "PT", Demonym="" },
                  new Country { Name = "Puerto Rico", Code = "PR", Demonym="" },
                  new Country { Name = "Qatar", Code = "QA", Demonym="" },
                  new Country { Name = "Reunion", Code = "RE", Demonym="" },
                  new Country { Name = "Romania", Code = "RO", Demonym="" },
                  new Country { Name = "Russian Federation", Code = "RU", Demonym="" },
                  new Country { Name = "RWANDA", Code = "RW", Demonym="" },
                  new Country { Name = "Saint Helena", Code = "SH", Demonym="" },
                  new Country { Name = "Saint Kitts and Nevis", Code = "KN", Demonym="" },
                  new Country { Name = "Saint Lucia", Code = "LC", Demonym="" },
                  new Country { Name = "Saint Pierre and Miquelon", Code = "PM", Demonym="" },
                  new Country { Name = "Saint Vincent and the Grenadines", Code = "VC", Demonym="" },
                  new Country { Name = "Samoa", Code = "WS", Demonym="" },
                  new Country { Name = "San Marino", Code = "SM", Demonym="" },
                  new Country { Name = "Sao Tome and Principe", Code = "ST", Demonym="" },
                  new Country { Name = "Saudi Arabia", Code = "SA", Demonym="" },
                  new Country { Name = "Senegal", Code = "SN", Demonym="" },
                  new Country { Name = "Serbia and Montenegro", Code = "CS", Demonym="" },
                  new Country { Name = "Seychelles", Code = "SC", Demonym="" },
                  new Country { Name = "Sierra Leone", Code = "SL", Demonym="" },
                  new Country { Name = "Singapore", Code = "SG", Demonym="" },
                  new Country { Name = "Slovakia", Code = "SK", Demonym="" },
                  new Country { Name = "Slovenia", Code = "SI", Demonym="" },
                  new Country { Name = "Solomon Islands", Code = "SB", Demonym="" },
                  new Country { Name = "Somalia", Code = "SO", Demonym="" },
                  new Country { Name = "South Africa", Code = "ZA", Demonym="" },
                  new Country { Name = "South Georgia and the South Sandwich Islands", Code = "GS", Demonym="" },
                  new Country { Name = "Spain", Code = "ES", Demonym="" },
                  new Country { Name = "Sri Lanka", Code = "LK", Demonym="" },
                  new Country { Name = "Sudan", Code = "SD", Demonym="" },
                  new Country { Name = "Suriname", Code = "SR", Demonym="" },
                  new Country { Name = "Svalbard and Jan Mayen", Code = "SJ", Demonym="" },
                  new Country { Name = "Swaziland", Code = "SZ", Demonym="" },
                  new Country { Name = "Sweden", Code = "SE", Demonym="" },
                  new Country { Name = "Switzerland", Code = "CH", Demonym="" },
                  new Country { Name = "Syrian Arab Republic", Code = "SY", Demonym="" },
                  new Country { Name = "Taiwan, Province of China", Code = "TW", Demonym="" },
                  new Country { Name = "Tajikistan", Code = "TJ", Demonym="" },
                  new Country { Name = "Tanzania, United Republic of", Code = "TZ", Demonym="" },
                  new Country { Name = "Thailand", Code = "TH", Demonym="" },
                  new Country { Name = "Timor-Leste", Code = "TL", Demonym="" },
                  new Country { Name = "Togo", Code = "TG", Demonym="" },
                  new Country { Name = "Tokelau", Code = "TK", Demonym="" },
                  new Country { Name = "Tonga", Code = "TO", Demonym="" },
                  new Country { Name = "Trinidad and Tobago", Code = "TT", Demonym="" },
                  new Country { Name = "Tunisia", Code = "TN", Demonym="" },
                  new Country { Name = "Turkey", Code = "TR", Demonym="" },
                  new Country { Name = "Turkmenistan", Code = "TM", Demonym="" },
                  new Country { Name = "Turks and Caicos Islands", Code = "TC", Demonym="" },
                  new Country { Name = "Tuvalu", Code = "TV", Demonym="" },
                  new Country { Name = "Uganda", Code = "UG", Demonym="" },
                  new Country { Name = "Ukraine", Code = "UA", Demonym="" },
                  new Country { Name = "United Arab Emirates", Code = "AE", Demonym="" },
                  new Country { Name = "United Kingdom", Code = "GB", Demonym="" },
                  new Country { Name = "United States", Code = "US", Demonym="" },
                  new Country { Name = "United States Minor Outlying Islands", Code = "UM", Demonym="" },
                  new Country { Name = "Uruguay", Code = "UY", Demonym="" },
                  new Country { Name = "Uzbekistan", Code = "UZ", Demonym="" },
                  new Country { Name = "Vanuatu", Code = "VU", Demonym="" },
                  new Country { Name = "Venezuela", Code = "VE", Demonym="" },
                  new Country { Name = "Viet Nam", Code = "VN", Demonym="" },
                  new Country { Name = "Virgin Islands, British", Code = "VG", Demonym="" },
                  new Country { Name = "Virgin Islands, U.S.", Code = "VI", Demonym="" },
                  new Country { Name = "Wallis and Futuna", Code = "WF", Demonym="" },
                  new Country { Name = "Western Sahara", Code = "EH", Demonym="" },
                  new Country { Name = "Yemen", Code = "YE", Demonym="" },
                  new Country { Name = "Zambia", Code = "ZM", Demonym="" },
                  new Country { Name = "Zimbabwe", Code = "ZW", Demonym="" }
        };

        public static IList<WorldCurrency> Currencies = new List<WorldCurrency>()
        {
            new WorldCurrency { Code = "AED", Name = "UAE dirham"  },
            new WorldCurrency { Code = "AFN", Name = "Afghan afghani"  },
            new WorldCurrency { Code = "ALL", Name = "Albanian lek"  },
            new WorldCurrency { Code = "AMD", Name = "Armenian dram"  },
            new WorldCurrency { Code = "ANG", Name = "Netherlands Antillean gulden"  },
            new WorldCurrency { Code = "AOA", Name = "Angolan kwanza"  },
            new WorldCurrency { Code = "ARS", Name = "Argentine peso"  },
            new WorldCurrency { Code = "AUD", Name = "Australian dollar"  },
            new WorldCurrency { Code = "AWG", Name = "Aruban florin"  },
            new WorldCurrency { Code = "AZN", Name = "Azerbaijani manat"  },
            new WorldCurrency { Code = "BAM", Name = "Bosnia and Herzegovina konvertibilna marka"  },
            new WorldCurrency { Code = "BBD", Name = "Barbadian dollar"  },
            new WorldCurrency { Code = "BDT", Name = "Bangladeshi taka"  },
            new WorldCurrency { Code = "BGN", Name = "Bulgarian lev"  },
            new WorldCurrency { Code = "BHD", Name = "Bahraini dinar"  },
            new WorldCurrency { Code = "BIF", Name = "Burundi franc"  },
            new WorldCurrency { Code = "BMD", Name = "Bermudian dollar"  },
            new WorldCurrency { Code = "BND", Name = "Brunei dollar"  },
            new WorldCurrency { Code = "BOB", Name = "Bolivian boliviano"  },
            new WorldCurrency { Code = "BRL", Name = "Brazilian real"  },
            new WorldCurrency { Code = "BSD", Name = "Bahamian dollar"  },
            new WorldCurrency { Code = "BTN", Name = "Bhutanese ngultrum"  },
            new WorldCurrency { Code = "BWP", Name = "Botswana pula"  },
            new WorldCurrency { Code = "BYR", Name = "Belarusian ruble"  },
            new WorldCurrency { Code = "BZD", Name = "Belize dollar"  },
            new WorldCurrency { Code = "CAD", Name = "Canadian dollar"  },
            new WorldCurrency { Code = "CDF", Name = "Congolese franc"  },
            new WorldCurrency { Code = "CHF", Name = "Swiss franc"  },
            new WorldCurrency { Code = "CLP", Name = "Chilean peso"  },
            new WorldCurrency { Code = "CNY", Name = "Chinese/Yuan renminbi"  },
            new WorldCurrency { Code = "COP", Name = "Colombian peso"  },
            new WorldCurrency { Code = "CRC", Name = "Costa Rican colon"  },
            new WorldCurrency { Code = "CUC", Name = "Cuban peso"  },
            new WorldCurrency { Code = "CVE", Name = "Cape Verdean escudo"  },
            new WorldCurrency { Code = "CZK", Name = "Czech koruna"  },
            new WorldCurrency { Code = "DJF", Name = "Djiboutian franc"  },
            new WorldCurrency { Code = "DKK", Name = "Danish krone"  },
            new WorldCurrency { Code = "DOP", Name = "Dominican peso"  },
            new WorldCurrency { Code = "DZD", Name = "Algerian dinar"  },
            new WorldCurrency { Code = "EEK", Name = "Estonian kroon"  },
            new WorldCurrency { Code = "EGP", Name = "Egyptian pound"  },
            new WorldCurrency { Code = "ERN", Name = "Eritrean nakfa"  },
            new WorldCurrency { Code = "ETB", Name = "Ethiopian birr"  },
            new WorldCurrency { Code = "EUR", Name = "European Euro"  },
            new WorldCurrency { Code = "FJD", Name = "Fijian dollar"  },
            new WorldCurrency { Code = "FKP", Name = "Falkland Islands pound"  },
            new WorldCurrency { Code = "GBP", Name = "British pound"  },
            new WorldCurrency { Code = "GEL", Name = "Georgian lari"  },
            new WorldCurrency { Code = "GHS", Name = "Ghanaian cedi"  },
            new WorldCurrency { Code = "GIP", Name = "Gibraltar pound"  },
            new WorldCurrency { Code = "GMD", Name = "Gambian dalasi"  },
            new WorldCurrency { Code = "GNF", Name = "Guinean franc"  },
            new WorldCurrency { Code = "GQE", Name = "Central African CFA franc"  },
            new WorldCurrency { Code = "GTQ", Name = "Guatemalan quetzal"  },
            new WorldCurrency { Code = "GYD", Name = "Guyanese dollar"  },
            new WorldCurrency { Code = "HKD", Name = "Hong Kong dollar"  },
            new WorldCurrency { Code = "HNL", Name = "Honduran lempira"  },
            new WorldCurrency { Code = "HRK", Name = "Croatian kuna"  },
            new WorldCurrency { Code = "HTG", Name = "Haitian gourde"  },
            new WorldCurrency { Code = "HUF", Name = "Hungarian forint"  },
            new WorldCurrency { Code = "IDR", Name = "Indonesian rupiah"  },
            new WorldCurrency { Code = "ILS", Name = "Israeli new sheqel"  },
            new WorldCurrency { Code = "INR", Name = "Indian rupee"  },
            new WorldCurrency { Code = "IQD", Name = "Iraqi dinar"  },
            new WorldCurrency { Code = "IRR", Name = "Iranian rial"  },
            new WorldCurrency { Code = "ISK", Name = "Icelandic kr\u00f3na"  },
            new WorldCurrency { Code = "JMD", Name = "Jamaican dollar"  },
            new WorldCurrency { Code = "JOD", Name = "Jordanian dinar"  },
            new WorldCurrency { Code = "JPY", Name = "Japanese yen"  },
            new WorldCurrency { Code = "KES", Name = "Kenyan shilling"  },
            new WorldCurrency { Code = "KGS", Name = "Kyrgyzstani som"  },
            new WorldCurrency { Code = "KHR", Name = "Cambodian riel"  },
            new WorldCurrency { Code = "KMF", Name = "Comorian franc"  },
            new WorldCurrency { Code = "KPW", Name = "North Korean won"  },
            new WorldCurrency { Code = "KRW", Name = "South Korean won"  },
            new WorldCurrency { Code = "KWD", Name = "Kuwaiti dinar"  },
            new WorldCurrency { Code = "KYD", Name = "Cayman Islands dollar"  },
            new WorldCurrency { Code = "KZT", Name = "Kazakhstani tenge"  },
            new WorldCurrency { Code = "LAK", Name = "Lao kip"  },
            new WorldCurrency { Code = "LBP", Name = "Lebanese lira"  },
            new WorldCurrency { Code = "LKR", Name = "Sri Lankan rupee"  },
            new WorldCurrency { Code = "LRD", Name = "Liberian dollar"  },
            new WorldCurrency { Code = "LSL", Name = "Lesotho loti"  },
            new WorldCurrency { Code = "LTL", Name = "Lithuanian litas"  },
            new WorldCurrency { Code = "LVL", Name = "Latvian lats"  },
            new WorldCurrency { Code = "LYD", Name = "Libyan dinar"  },
            new WorldCurrency { Code = "MAD", Name = "Moroccan dirham"  },
            new WorldCurrency { Code = "MDL", Name = "Moldovan leu"  },
            new WorldCurrency { Code = "MGA", Name = "Malagasy ariary"  },
            new WorldCurrency { Code = "MKD", Name = "Macedonian denar"  },
            new WorldCurrency { Code = "MMK", Name = "Myanma kyat"  },
            new WorldCurrency { Code = "MNT", Name = "Mongolian tugrik"  },
            new WorldCurrency { Code = "MOP", Name = "Macanese pataca"  },
            new WorldCurrency { Code = "MRO", Name = "Mauritanian ouguiya"  },
            new WorldCurrency { Code = "MUR", Name = "Mauritian rupee"  },
            new WorldCurrency { Code = "MVR", Name = "Maldivian rufiyaa"  },
            new WorldCurrency { Code = "MWK", Name = "Malawian kwacha"  },
            new WorldCurrency { Code = "MXN", Name = "Mexican peso"  },
            new WorldCurrency { Code = "MYR", Name = "Malaysian ringgit"  },
            new WorldCurrency { Code = "MZM", Name = "Mozambican metical"  },
            new WorldCurrency { Code = "NAD", Name = "Namibian dollar"  },
            new WorldCurrency { Code = "NGN", Name = "Nigerian naira"  },
            new WorldCurrency { Code = "NIO", Name = "Nicaraguan c\u00f3rdoba"  },
            new WorldCurrency { Code = "NOK", Name = "Norwegian krone"  },
            new WorldCurrency { Code = "NPR", Name = "Nepalese rupee"  },
            new WorldCurrency { Code = "NZD", Name = "New Zealand dollar"  },
            new WorldCurrency { Code = "OMR", Name = "Omani rial"  },
            new WorldCurrency { Code = "PAB", Name = "Panamanian balboa"  },
            new WorldCurrency { Code = "PEN", Name = "Peruvian nuevo sol"  },
            new WorldCurrency { Code = "PGK", Name = "Papua New Guinean kina"  },
            new WorldCurrency { Code = "PHP", Name = "Philippine peso"  },
            new WorldCurrency { Code = "PKR", Name = "Pakistani rupee"  },
            new WorldCurrency { Code = "PLN", Name = "Polish zloty"  },
            new WorldCurrency { Code = "PYG", Name = "Paraguayan guarani"  },
            new WorldCurrency { Code = "QAR", Name = "Qatari riyal"  },
            new WorldCurrency { Code = "RON", Name = "Romanian leu"  },
            new WorldCurrency { Code = "RSD", Name = "Serbian dinar"  },
            new WorldCurrency { Code = "RUB", Name = "Russian ruble"  },
            new WorldCurrency { Code = "SAR", Name = "Saudi riyal"  },
            new WorldCurrency { Code = "SBD", Name = "Solomon Islands dollar"  },
            new WorldCurrency { Code = "SCR", Name = "Seychellois rupee"  },
            new WorldCurrency { Code = "SDG", Name = "Sudanese pound"  },
            new WorldCurrency { Code = "SEK", Name = "Swedish krona"  },
            new WorldCurrency { Code = "SGD", Name = "Singapore dollar"  },
            new WorldCurrency { Code = "SHP", Name = "Saint Helena pound"  },
            new WorldCurrency { Code = "SLL", Name = "Sierra Leonean leone"  },
            new WorldCurrency { Code = "SOS", Name = "Somali shilling"  },
            new WorldCurrency { Code = "SRD", Name = "Surinamese dollar"  },
            new WorldCurrency { Code = "SYP", Name = "Syrian pound"  },
            new WorldCurrency { Code = "SZL", Name = "Swazi lilangeni"  },
            new WorldCurrency { Code = "THB", Name = "Thai baht"  },
            new WorldCurrency { Code = "TJS", Name = "Tajikistani somoni"  },
            new WorldCurrency { Code = "TMT", Name = "Turkmen manat"  },
            new WorldCurrency { Code = "TND", Name = "Tunisian dinar"  },
            new WorldCurrency { Code = "TRY", Name = "Turkish new lira"  },
            new WorldCurrency { Code = "TTD", Name = "Trinidad and Tobago dollar"  },
            new WorldCurrency { Code = "TWD", Name = "New Taiwan dollar"  },
            new WorldCurrency { Code = "TZS", Name = "Tanzanian shilling"  },
            new WorldCurrency { Code = "UAH", Name = "Ukrainian hryvnia"  },
            new WorldCurrency { Code = "UGX", Name = "Ugandan shilling"  },
            new WorldCurrency { Code = "USD", Name = "United States dollar"  },
            new WorldCurrency { Code = "UYU", Name = "Uruguayan peso"  },
            new WorldCurrency { Code = "UZS", Name = "Uzbekistani som"  },
            new WorldCurrency { Code = "VEB", Name = "Venezuelan bolivar"  },
            new WorldCurrency { Code = "VND", Name = "Vietnamese dong"  },
            new WorldCurrency { Code = "VUV", Name = "Vanuatu vatu"  },
            new WorldCurrency { Code = "WST", Name = "Samoan tala"  },
            new WorldCurrency { Code = "XAF", Name = "Central African CFA franc"  },
            new WorldCurrency { Code = "XCD", Name = "East Caribbean dollar"  },
            new WorldCurrency { Code = "XDR", Name = "Special Drawing Rights"  },
            new WorldCurrency { Code = "XOF", Name = "West African CFA franc"  },
            new WorldCurrency { Code = "XPF", Name = "CFP franc"  },
            new WorldCurrency { Code = "YER", Name = "Yemeni rial"  },
            new WorldCurrency { Code = "ZAR", Name = "South African rand"  },
            new WorldCurrency { Code = "ZMK", Name = "Zambian kwacha"  },
            new WorldCurrency { Code = "ZWR", Name = "Zimbabwean dollar"  }

     };

        public static IList<GenericType> GenericParameters = new List<GenericType>()
    {
            new GenericType { Id=1,  Code = "BSD01",Type = "BSD" ,Name = "BASIC",Status = true},
            new GenericType { Id=2,  Code = "BSD02",Type = "BSD",Name = "GROSS",Status = true},
            new GenericType { Id=3,  Code = "BSD03",Type = "BSD",Name = "NET",Status = true},

            new GenericType { Id=(int)PBS.FIXED_AMOUNT,  Code = "PBS01",Type = "PBS",Name = "Fixed Amount",Status = true},
            new GenericType { Id=(int)PBS.PERCENTAGE_OF_NET,  Code = "PBS02",Type = "PBS",Name = "Percentage of Net",Status = true},

            new GenericType { Id=1,  Code = "BST01",Type = "BST",Name = "SALARY",Status = true},
            new GenericType { Id=2,  Code = "BST02",Type = "BST",Name = "WAGES",Status = true},

            new GenericType { Id=(int)FAT.FLATAMOUNT,  Code = "FAT01",Type = "FAT", Name = "Flat Amount",  Status = true },
            new GenericType { Id=(int)FAT.PERCENTAGEOFBASIC,  Code = "FAT02",Type = "FAT", Name = "Percentage of Basic",Status = true },

            new GenericType { Id=(int)GND.MALE,  Code = "GND01",Type = "GND", Name = "Male",  IsCustomType=true, Status = true },
            new GenericType { Id=(int)GND.FEMALE,  Code = "GND02",Type = "GND", Name = "Female", IsCustomType=true, Status = true },

            new GenericType { Id=(int)MST.MARRIED, Code = "MST01",Type = "MST", Name = "MARRIED",  Status = true },
            new GenericType { Id=(int)MST.SINGLE, Code = "MST02",Type = "MST", Name = "SINGLE",  Status = true },
            new GenericType { Id=(int)MST.DIVORCED, Code = "MST03",Type = "MST", Name = "DIVORCED", Status = true },
            new GenericType { Id=(int)MST.WIDOWED, Code = "MST04",Type = "MST", Name = "WIDOWED", Status = true },
            new GenericType { Id=(int)MST.SEPERATED, Code = "MST05",Type = "MST", Name = "SEPERATED", Status = true },

            new GenericType { Id=(int)PFQ.RECURRING, Code = "PFQ01",Type = "PFQ", Name = "RECURRING",  Status = true },
            new GenericType { Id=(int)PFQ.NONRECURRING, Code = "PFQ02",Type = "PFQ", Name = "NON-RECURRING", Status = true },

            new GenericType { Id=(int)OBS.OVERTIME, Code = "OBS01",Type = "OBS", Name = "Overtime",  Status = true },
            new GenericType { Id=(int)OBS.BONUS, Code = "OBS02",Type = "OBS", Name = "Bonus", Status = true },
            new GenericType { Id=(int)OBS.SHIFT, Code = "OBS03",Type = "OBS", Name = "Shift", Status = true },
            new GenericType { Id=(int)OBS.GENERAL, Code = "OBS04",Type = "OBS", Name = "General", Status = true },

            new GenericType { Id=1, Code = "IDT01",Type = "IDT", Name = "INCREASE", Status = true },
            new GenericType { Id=2, Code = "IDT02",Type = "IDT", Name = "DECREASE", Status = true },

            new GenericType { Id=(int)LST.EMPLOYER, Code = "LST01",Type = "LST", Name = "Employer", Status = true },
            new GenericType { Id=(int)LST.THIRD_PARTY, Code = "LST02",Type = "LST", Name = "Third-party", Status = true },

            new GenericType { Id=(int)IRT.FIXED, Code = "IRT01",Type = "IRT", Name = "Fixed", Status = true },
            new GenericType { Id=(int)IRT.VARIABLE, Code = "IRT02",Type = "IRT", Name = "Variable", Status = true },

            new GenericType { Id=(int)ICR.ANNUAL, Code = "ICR01",Type = "ICR", Name = "ANNUAL", Status = true },
            new GenericType { Id=(int)ICR.SIMPLE, Code = "ICR02",Type = "ICR", Name = "SIMPLE", Status = true },
            new GenericType { Id=(int)ICR.ABSOLUTE, Code = "ICR03",Type = "ICR", Name = "ABSOLUTE", Status = true },

            new GenericType { Id=(int)ORG.DEP, Code = "ORG01",Type = "ORG", Name = "Department",  Status = true },
            new GenericType { Id=(int)ORG.DIV, Code = "ORG02",Type = "ORG", Name = "Division",  Status = true },
            new GenericType { Id=(int)ORG.EMT, Code = "ORG03",Type = "ORG", Name = "Employee Type",  Status = true },
            new GenericType { Id=(int)ORG.SEC, Code = "ORG04",Type = "ORG", Name = "Section", Status = true },
            new GenericType { Id=(int)ORG.LOC, Code = "ORG05",Type = "ORG", Name = "Location",  Status = true },
            new GenericType { Id=(int)ORG.UNI, Code = "ORG06",Type = "ORG", Name = "Unit", Status = true },
            new GenericType { Id=(int)ORG.POS, Code = "ORG07",Type = "ORG", Name = "Position", Status = true },

            new GenericType { Id=1, Code = "RLA01",Type = "RLA", Name = "WIFE",  Status = true },
            new GenericType { Id=2, Code = "RLA02",Type = "RLA", Name = "SON", Status = true },
            new GenericType { Id=3, Code = "RLA03",Type = "RLA", Name = "DAUGHTER", Status = true },
            new GenericType { Id=4, Code = "RLA04",Type = "RLA", Name = "FATHER", Status = true },
            new GenericType { Id=5, Code = "RLA05",Type = "RLA", Name = "MOTHER", Status = true },

            new GenericType { Id=(int)SAT.HOURLY, Code = "SAT01",Type = "SAT",  Name = "Hourly",  Status = true },
            new GenericType { Id=(int)SAT.DAILY, Code = "SAT02",Type = "SAT",  Name = "Daily",  Status = true },
            new GenericType { Id=(int)SAT.WEEKLY, Code = "SAT03",Type = "SAT",  Name = "Weekly", Status = true },
            new GenericType { Id=(int)SAT.MONTHLY, Code = "SAT04",Type = "SAT",  Name = "Monthly", Status = true },
            new GenericType { Id=(int)SAT.ANNUALLY, Code = "SAT05",Type = "SAT",  Name = "Annually", Status = true },

            new GenericType { Id=1, Code = "TIL01",Type = "TIL",  Name = "MR.", IsCustomType=true , Status = true},
            new GenericType { Id=2, Code = "TIL02",Type = "TIL",  Name = "MRS.", IsCustomType=true ,Status = true},
            new GenericType { Id=3, Code = "TIL03",Type = "TIL",  Name = "MISS", IsCustomType=true ,Status = true  },
            new GenericType { Id=4, Code = "TIL04",Type = "TIL",  Name = "DR.", IsCustomType=true , Status = true  },
            new GenericType { Id=5, Code = "TIL05",Type = "TIL",  Name = "PROF", IsCustomType=true ,  Status = true  },

            new GenericType { Id=(int)BAS.VARYINGAMOUNT, Code = "BAS01",Type = "BAS",  Name = "VARYING AMOUNT",  Status = true },
            new GenericType { Id=(int)BAS.FLATAMOUNT, Code = "BAS02",Type = "BAS",  Name = "FLAT AMOUNT",  Status = true },
            new GenericType { Id=(int)BAS.PERCENTAGEOFBASICSALARY, Code = "BAS03",Type = "BAS",  Name = "PERCENTAGE OF BASIC SALARY",  Status = true },
            new GenericType { Id=(int)BAS.PERCENTAGEOFDAILYRATE, Code = "BAS04",Type = "BAS",  Name = "PERCENTAGE OF DAILY RATE",  Status = true },
            new GenericType { Id=(int)BAS.PERCENTAGEOFHOURLYRATE, Code = "BAS05",Type = "BAS",  Name = "PERCENTAGE OF HOURLY RATE",  Status = true },
            new GenericType { Id=(int)BAS.PERCENTAGEOFGROSSSALARY, Code = "BAS06",Type = "BAS",  Name = "PERCENTAGE OF GROSS SALARY",  Status = true },
            new GenericType { Id=(int)BAS.PERCENTAGEOFANNUALSALARY, Code = "BAS07",Type = "BAS",  Name = "PERCENTAGE OF ANNUAL SALARY",  Status = true },
            new GenericType { Id=(int)BAS.PERCENTAGEOFTOTALCASHEMOLUMENT, Code = "BAS08",Type = "BAS",  Name = "PERCENTAGE OF TOTAL CASH EMOLUMENT",  Status = true },
            

            new GenericType { Id=1, Code = "SCR01",Type = "SCR",  Name = "VARYING AMOUNT",  Status = true },
            new GenericType { Id=2, Code = "SCR02",Type = "SCR",  Name = "FLAT AMOUNT",  Status = true },
            new GenericType { Id=3, Code = "SCR03",Type = "SCR",  Name = "PERCENTAGE BASED ON",  Status = true },

            new GenericType { Id=1, Code = "STS01",Type = "STS", Name = "ACTIVE",  Status = true },
            new GenericType { Id=2, Code = "STS02",Type = "STS", Name = "INACTIVE", Status = true },

            new GenericType { Id=1, Code = "PYO01",Type = "PYO", Name = "BANK", Status = true },
            new GenericType { Id=2, Code = "PYO02",Type = "PYO", Name = "MOMO", Status = true },
            new GenericType { Id=3, Code = "PYO03",Type = "PYO", Name = "CASH", Status = true },

            new GenericType { Id=(int)ESP.FLATAMOUNT, Code = "ESP01",Type = "ESP", Name = "FLAT AMOUNT", Status = true },
            new GenericType { Id=(int)ESP.PERCENTAGEOFBASIC, Code = "ESP02",Type = "ESP", Name = "PERCENTAGE OF BASIC", Status = true },
            new GenericType { Id=(int)ESP.ACTIVE, Code = "ESP03",Type = "ESP", Name = "ACTIVE", Status = true },
            new GenericType { Id=(int)ESP.INACTIVE, Code = "ESP04",Type = "ESP", Name = "INACTIVE", Status = true },
            new GenericType { Id=(int)ESP.TERMINATED, Code = "ESP05",Type = "ESP", Name = "TERMINATED", Status = true },
            new GenericType { Id=(int)ESP.NOSALARY, Code = "ESP06",Type = "ESP", Name = "NO SALARY", Status = true },

            new GenericType { Id=(int)ACT.INCREASE, Code = "ACT01",Type = "ACT",  Name = "INCREASE",  Status = true },
            new GenericType { Id=(int)ACT.DECREASE, Code = "ACT02",Type = "ACT",  Name = "DECREASE",  Status = true },


            new GenericType { Id=(int)TDC.DATE, Code = "TDC01",Type = "TDC", Name = "Date", Status = true },
            new GenericType { Id=(int)TDC.HOURS_WORKED_DAYS, Code = "TDC02",Type = "TDC", Name = "Hrs. worked/Days", Status = true },
            new GenericType { Id=(int)TDC.ACTIVITY, Code = "TDC03",Type = "TDC", Name = "Activiy", Status = true },
            new GenericType { Id=(int)TDC.ABSENT_HOURS, Code = "TDC04",Type = "TDC", Name = "Absent Hours", Status = true },

            new GenericType { Id=(int)PYT.REGULAR,  Code = "PYT01",Type = "FPY", Name = "Regular",  Status = true },
            new GenericType { Id=(int)PYT.ADHOC,  Code = "PYT02",Type = "PYT", Name = "Ad-hoc",Status = true },

            new GenericType { Id=(int)RTX.GENERAL,  Code = "RTX01",Type = "RTX", Name = "General",  Status = true },
            new GenericType { Id=(int)RTX.BONUS,  Code = "RTX02",Type = "RTX", Name = "Bonus",Status = true },  
            new GenericType { Id=(int)RTX.OVERTIME,  Code = "RTX03",Type = "RTX", Name = "Overtime",  Status = true },


        };

        public static IList<GenericType> GenericElementType = new List<GenericType>() 
        {
            new GenericType { Id=1,  Code = "ELT01",Type = "ELT" ,Name = "Accommodation with Furnishing", Status = true},
            new GenericType { Id=2,  Code = "ELT02",Type = "ELT",Name = "Accommodation Only", Status = true},
            new GenericType { Id=3,  Code = "ELT03",Type = "ELT",Name = "Furnishing Only", Status = true},
            new GenericType { Id=4,  Code = "ELT04",Type = "ELT",Name = "Shared Accommodation", Status = true},
            new GenericType { Id=5,  Code = "ELT05",Type = "ELT",Name = "Driver and Vehicle with Fuel", Status = true},
            new GenericType { Id=6,  Code = "ELT06",Type = "ELT",Name = "Vehicle Only", Status = true},
            new GenericType { Id=7,  Code = "ELT07",Type = "ELT",Name = "Fuel only", Status = true},
        };
    }
}
